project:
  title: "Inaugural Lecture Slides"
  output-dir: ../_site/

format:
  revealjs:
    output-file: index.html
    theme: dark
    css: styles.css
    slide-number: true
    controls: true
    progress: true
    history: true
    navigation-mode: grid
    transition: none
    incremental: false
    center: false
    slide-level: 2
