# Part two: Reproducibility and Reliability in Computational Science

## 2.1 The Avoiding Mass Extinctions Engine
::: notes

Fast forward a few years, to 2009. I'm outside academia for a while, working for a startup doing climate impact modelling - the name of the company was AMEE - the "Avoiding Mass Extinctions Engine". It's a for-profit social enterprise - with a mission to save the world, and make a bob or two doing it. [AMEE bug logo] [Climate matrix symbol]

This really suits me politically - I'm uncomfortable not working for mission/purpose - I want my jobs to be 'for good', but I also like the sense of building a product, of demonstrating that you've got something of real value. This will be important later when we talk about approaches to verifiable understanding.

What our product does is not model the climate - we model polluters. E.g. a computer programme that tells me "if I build a big computer, how much will it harm the climate?" The point here is that Obama was about to pass climate tax legislation, and if that had happened, it would have put such models in the financial-services-business-planning loop.

:::

## 2.2 Climategate
::: notes

In 2009, a group of researchers building computer models of climate at UEA were hacked by climate denialists. In addition to taking various email comments out of context to undermine the science, the hackers exploited bug reports in those emails. Issues with developing computer simulations - part of the work I described in the previous section - were played up to undermine trust in climate science.

As a result of this - a manufactured scandal arising from a hostile disinformation campaign - but with a kernal of truth in the need to improve scientific practice when using software as a critical research instrument - investers were no longer willing to invest in "cleantech" for a while - digital startups working on climate adaptation and mitigation - and AMEE failed.

This really struck a chord with me. There were genuine - innocent - mistakes in the model programming. But there were examples of things where a more careful approach to programming would have prevented these.
And where science is a political football - being used to make decisions that matter for the future of the world - we need to work very carefully - bend over backward - to be very sure our science - and thus the code that drives it - is correct.

By this time I'd realised that my PhD software was also very buggy and badly engineered I should add. My successor in Prof Webber's lab had a lot of tidying up to do! (Sorry.)

:::

## 2.3 The Joint Biosecurity Centre
::: notes

As another example of the importance of trustworthiness in scientific code, during the covid crisis I was a senior advisor at the Joint Biosecurity Centre, building the team that did the modelling that put together
the national R number - remember that?

One of the things that concerned me was that, at the beginning of the crisis, the models that were being used were running in the universities that built them. This was a risk, partly because university
systems aren't designed for the kind of reliability that national crisis resilience requires. But also because of the reputational risk to the university sector of operational decision making being done through
codes that were designed for research purposes, often without the kind of robust engineering practices I've been working to spread through academia.

I'm proud that I was able to help colleagues navigate the challenge of getting these codes moved to a national shared secure resource, while still benefitting from the understanding developed within the
higher education sector.

<illustration>

:::

## 2.4 The reproducibility crisis
::: notes

Given the complexity of the task of effectively using computers in research, it is no wonder we run into these challenges.

We've just seen examples of where science reaches out from the task of understanding the world to become important in looking after the world, and thus the importance of computational reliability.

But problems with reliability in computationally driven science don't just undermine the correctness of our practical advice or public trust. They undermine the goal of science - to find ways to approach true understandings of the world.

Science, in it's self-conception, views reproducibility - the idea that a paper should enable another scientist to run the same study and verify the conclusion - as an important part of why the so-called scientific method works.

There's growing evidence that across many disciplines this ideal is far from realised.

One might hope that in computational science, where a program constitutes a formal, unambiguous script which describes the model and how it was used, reproducibility would be higher. In fact there reasonable arguments that it's no better, and perhaps worse. [https://pmc.ncbi.nlm.nih.gov/articles/PMC8530091/?utm_source=chatgpt.com]

If you work in computational science you'll have come across loads of these. Genes being automatically renamed by excel to months because they both have three letter codes is one popular example. I've seen - no names today to protect the guilty - published content in a nature paper that was based on numbers where two very large numbers were subtracted from each other - what we call in the trade a 'floating point underflow' - essentially random. It was not retracted.

So we have learned: **we need to build our computer systems for science carefully**, to ensure our science is trustworthy.

:::


## 2.5 What is engineering?
::: notes

There is a name for the methods humans have come up with to allow us to build things reliably: Engineering.

There are lots of different definitions of engineering around, but one I favour runs something like:

**the tools, practices and systems that enable repeatable, reliable, safe and scalable technical construction**

It's about how we come up with ways to, given our flawed human natures, make things that don't break all the time!

As scientists, we are concerned with understanding the world. 

As engineers, we are concerned not just with wisely using our understanding to make changes to the world that are beneficial, but building ways of working that sustain and protect those benefits.

[Illustration - earthquake]

:::

## 2.6 Software Engineering
::: notes

Software systems now govern our lives, and, as a society, in practice we are *terrible* at it.

[Illustration - post office scandal.]

However, a large body of practice, around testing, documentation, change management and so on has emerged. Applied carefully, these help make it less likely that our software systems will harm us.

It's important for practitioners to know and follow these codes when building code that "matters". I'm a Fellow of The British Computer Society - the UK's professional
institute for information technolgy.

As with other areas of engineering, these include both the highly technical and things that are more like management science, and the interaction between them. For example, "agile project management"
techniques grew up within software engineering.

:::

## 2.7 Not just *software* engineering
::: notes

Now, software is not the only aspect of computational science - we've talked about the hardware and network engineering of warehouse-scale computers. 

Computational statistics - these days we call it "data science" - is another aspect of computing with an evolved, but patchily applied system of professional practice. As computing has evolved,
the statistical profession and the computer programming profession have experienced a complex interplay, with rules of practice evolving in response. 

The BCS and the Royal Statistical society work together to build professional practices for data science.

The data itself, is also a key part of this - librarianship is a long-standing professional practice, and the new profession of data stewardship is emerging - a computational librarian of data.

All of these are just as critical to effective computational science and are in scope of the emerging discipline we're trying to describe here.

:::

## 2.8 Ethics and Engineering
::: notes

A key part of any engineering practice is a sustained ethical framework, and mechanisms for professional practice that ensure that these ethics are upheld. 

I would like to imagine that you haven't reached real professional status as an engineer until you've refused to build something in ways that violate these codes.

I won't go into details in public, but as a data scientist working in the covid response in the UK government, I have achieved this.

[Illustration - phrenology]

:::

## 2.9 The Research Software Engineer and the rise of UCL ARC
::: notes

In 2012 - following some postdocing, and the mathworks, and the climate start up failed, and, needing a job, I came back to academia to do the brain blood flow postdoc with Peter.

With these kind of thoughts around the ethics and practices of engineering and science, I began, with others to think about what kind of intervention might help the reliability and trustworthiness of computational science.

We hypothesised that a professional community of engineers would be necessary for efficient, productive and trustworthy research, given the accelerating importance of computing in science. 

There are now thousands of people around the world employed as part of this set of professions I helped to invent, and a team of a bit less than 150 at UCL, in the UCL Advanced Research Computing Centre, which I lead.

[illustration]

Probably a lot of the reason I'm standing here is the success of this idea - we'll talk more in a moment about whether that's a scientific achievement or not. 

:::

## 2.10 The data empowered society
::: notes

Considered thus, engineering is part of management science, and a social science. 

Sometimes it helps to know some science - but what engineering adds is this layer of tools and approaches, and these are designed in the context of human behaviour and human motivations.

I think this is part of what I bring to my role as co-pro-vice-provost of UCL's Grand Challenge of Data Empowered Societies. 

I'm not a social scientist, but as a practicing engineering leader, I've 
played a significant role in building the social systems that control engineering in computational research. I've been at the sharp end of these issues, and hope that that practical knowledge can help
with the challenge of making the role of data and computers and software in society safe.

:::

## 2.11 Science and Engineering
::: notes

In the previous section, we talked about professional engineering. I gave examples of long standing and emerging professions in computing - information technology. These professions exist outside the
scientific context - in software and data companies selling cars and T-shirts, in news websites and in the civil service.

I want to dig for a moment into the relationship of science and engineering, touching on four aspects of the relationship.

:::

## 2.12 Science-for-engineering
::: notes

People often think about the question of science-for-engineering: using an understanding of the world, built up from the tools of science, to build useful things to help us manage and control the world.

We've seen examples of this already with climate modelling and covid modelling. It's actually a moderately controversial point as to whether science is that important for engineering. A lot of technologies have been built by trial and error without understanding the science behind them.

[Diagrammatic models of the science-engineering relationship]

Personally, in my work I'm primarily motivated by computational science for science - understanding the world - rather than computational science as a means to technology.

We've seen that in the model-simulation continuum, simulation is of primary utility for engineering, while modelling is of primary utility for science, though this is *not* clear cut.

You'll see that my forays into application are usually driven by a sense of accountability - where the technologies that are related to the science have risks or benefits that matter enough to the world that we have a duty as scientists to be concerned with them.

:::

## 2.13 Engineering-for-science
::: notes

It's also the case that advances in scientific understanding are often driven by engineering goals. Our Boids example - the flocking behaviour - was motivated first by the need to make things that *look like* flocks of birds, for special effects in movies, and then only later applied to animal behaviour as a science!

This is also highly motivating - the role of the application is not only to deliver a technology, but to act as a driver of science. This is a highly signficant feedback loop, and a major part of the real story of how science proceeds.

[Building up a diagram as we go]

:::

## 2.14 Engineering studied scientifically
::: notes

There's a different flavour of science-for-engineering. Not the use of understanding that emerged from science to help with engineering challenges, but rather, the application of the scientific method to discover which tools, practices and systems of engineering, are effective. We can use rigorous methods to investigate questions of which kind of CAD tool is best for building cars, or which structure of an engineering
company delivers most reliably. We'll extensively discuss such approaches in a moment.

:::

## 2.15 Engineering applied to science
::: notes

While all four of these touch my research practice, the fourth category is the one I'm most interested in: the application of engineering to the tools of science? Sometimes this is called "instrument science": 
how best do we build a telescope? A supercollider?

In the first part of the lecture, I tried to convince you that scientific simulation codes, and the computers they run on, are one such interesting engineering challenge in science. How best do we write
trustworthy computer code to be applied as part of the scientific endeavour, and how do we design that alongside the computers it will run on? (We call this "co-design" of software and hardware.)

:::

## 2.16 Definition
::: notes

So now we're ready to define what I'm interested in - what I claim to be a professor of!

Science is the use of systematic methods to avoid lying to ourselves when trying to understand the world - more on this in a moment.

(When I say the world I mean the human and built worlds as well as the natural world - economics counts.)

Computational science is doing science using information technologies - software, computers and data - as a primary research instrument.

Engineering is the development of tools, practices and systems for the efficient, trustworthy, ethical and safe generation and maintainance of technologies.
Computer engineering is the development and application of those tools and practics to information technology.

Engineering Computational Science is, therefore, the development and application of tools, practices and systems for the efficient,
trustworthy, ethical and safe use of information technologies as part of trying to understand the world.

So now you know what I do.

:::

## 2.17 Why is this particularly interesting?
::: notes

Science and scholarship are more interesting than most other things people do... (I would be happy to be into programming for the arts or sport, but not selling widgets...), and you get to study those things when trying to make software about them, including some quite hard maths, which I like, given my background in theoretical physics.

But there's a more interesting reason than that: Research IT has additional measures of value which have to be optimised for besides performance (running fast) and maintainability. The usual reason programmers try to
write lucid code is given as maintainability - code which is hard to understand is hard to look after, update and catch bugs in. That's certainly true.

But in research, the code is not just a "thing to get a computer to do what you want". It is itself an accurate description of the algorithm you're carrying out - often the only accurate one - and as such a key part of the
scientific process - reproducibility. It's also a key part of *understanding* a system - the modelling-as-part-of-securing-your-understanding concept I began the lecture with. 

They're also a vital part of teaching about it - well written software has pedagogical value.

And they play a role in the politicised aspects of computational science that I've referred to - transparency, but also, interestingly, openness to public engagement and widening access to participation in the
research process.

It's these additional aspects of the duties of IT when it forms part of a research process that makes it interesting to me. Research instruments are *never* purely tools, they are always bound up in the study, enfolded within the knowledge production process. Thus the engineering of research instruments - from telescopes to sequencing machines to supercomputers - is a particularly interesting engineering-science problem.

:::

## 2.18 Epistemic cultures
::: notes

We need to think for a moment about how we might study of this field.

I remember vividly arriving at university and having my naive, untroubled view of science as a formal, clean way of building understanding of the world absolutely demolished. (This is one of the reasons why it's important to have inter-academic-cultural dialogue across student populations.) I think (except among fundamentalist or propaganda groups who have never practiced in a university), it is quite generally accepted that science is a messy, complex social process.

I do believe - and I think there's ample evidence - that whatever science is, however it works, does work well to help us build understanding. But it's not at all like the simplistic hypothesis-test-theory charicature. We've already seen one example of the richer and more complicated nature of how science moves forward by considering engineering-for-science, science-for-engineering, and engineering science.

For me, there are many different tricks to how we *avoid lying to ourselves*. Sociologists of science call these 'epistemic cultures'.

Anyone who is using any of these careful practices to avoid self-deception can reasonably be said, I think, to be doing science. (Some would prefer scholarship, or another term, that's fine,
my only beef is with epistemic exclusionists.)

Over-obsession with a particular epistemology - theory of knowledge - way of building truth, is naive "scientism" - science as a fundamentalist religion, not as science.

:::

## 2.19 Epistemic pluralism
::: notes

The randomised clinical trial is by far from the only valid research methodology. Don't get me wrong, I love RCTs, and there are colleagues who are making great progress by finding new ways to apply them outside medicine.

But there are rigorous research disciplines that reason from observation, without experiment - like some parts of astronomy. 

There are cultures that learn through deep engagement with small sources - close reading in the humanities for example, or rigourous qualitative research in the social sciences or economics through interview-based methodologies. 

There are whole sub-fields of physics that primarily develop through mathematical reasoning and only occasional access to new data, but make progress from a focus on parsimonious explanation - elegant theories evolving from a heuristic of mathematical beauty. We could spend ages talking about Science vs Wissenschaft.

Complexity science - exploring the world by writing down rules and exploring their consequences computationally - is another such important epistemology. Hugely scientific, but because we don't evaluate on the 
basis of formal comparison with experiment, but by drawing conclusions based on evaluation of the feel of elegance and explanatory power - not a match to the classical "scientific" charicature. The emergence of
computer simulation, the other part of the third paradigm, alongside experimentation and elegance-seeking mathematical reasoning, is another.

My view is that our work of knowledge production is constantly developing new tools, all of which, so long as they are based on some kind of approach to self-deception-limiting, are valid parts of scientific inquiry.

As we discover new research disciplines, we therefore need to ask, what will be effective self-deception-limiting ways of working, appropriate to the challenges of that domain.

:::

## 2.20 The Empirical Software Engineering epistemology
::: notes

One powerful approach, but one I do not make use of in my own work - not because I don't believe in it, but just because it doesn't suit my temperament - is the empirical software engineering approach. I need to
explain it carefully now, by way of explaining what my wonderful colleagues who work in this way do, so that I can explain how my approaches differ.

In this approach, scholars engage in systematic studies of large bodies of software engineering work - and contrast the effectiveness of various engineering methodologies. One can, for example, look across all the
open source code in the world, compare different testing practices, and see which result in higher bug generation rates. This is a well-established approach, and produces interesting and useful results.

One can also deliberately make interventions - such as give a subset of projects free access to some research software engineers - and observe the results, approximating a controlled trial. Again, fascinating, but not my thing.

:::

## 2.21 The Tinkerer's epistemology
::: notes

The primary methodology applied within the computational science cultures I grew up in - theoretical physics, high performance computing, and computational biology - is what I call the Tinkerer's Epistemology.
One observes a challenge, develops a hypothesis for a software tool, or more commonly, a modification to an existing software tool, which would make it work better, (produce results faster or more accurately).

With existing tools, this approach can often have the nice property of being self-verifying: one can immediately see whether a change makes a positive impact to a metric such as simulation result time, and include the graph in a publication. This is highly emotionally satisfying, but as we shall see it also has important properties when we consider the future of the domain, as we shall see in the third part of the lecture.

Now, many code changes can have multiple effects on different metrics - reducing lucidity (and thus maintainability, trustworthiness or pedagogical value) - while improving performance. And such additional concerns
are not self-verifying. Thus the tinkerer's epistemology - "What Works?" - is flawed when we consider these aspects.

:::

## 2.22 The Service Provider's epistemology
::: notes

I can therefore now turn to *why*, in 2012, when working on the brain bloodflow codes, I formed the research software group in UCL as part of what many would frame as "IT support", of all things.

<illustration - IT crowd>

I was feeling that I needed a bit more verifiable utility and impact in work on computational science tools, and needed the rigor that **customers** bring to the evidence basis.

Now, there's a lot wrong with service culture when applied to the research process - because, as I have argued, the tools are part of the research process, they can't be safely externalised - outsourced - 
from the scientific endeavour.

But there's a lot of value in **market data** in evidencing the value of contributions to the research process - and potential that this works for the non-self-verifying aspects of cultural and management
interventions - such as developing the role of the research software engineer. The market success of the research software engineer intervention, therefore, becomes part of the evidence basis for the
correctness of this conjecture.

I'm by no means the first to take this step in combining instrument science with service provision as a research methodology. Some labs - constructed as labs, within the research culture - such as the
Diamond Light Source, or the European Molecular Biology Laboratory - have been doing it for years.

:::

## 2.23 Research IT and instrument science
::: notes

However, there's been a challenge in doing this in the context of software-as-a-research-instrument. There's been an evolution in universities for core IT - the IT that manages the payroll and does the email -
to move away from the academic functions of the university and be established as a professional service. This is for good reasons - there's no particular reason for these to be part of the academic culture,
unlike for research instruments.

What we've been able to establish in UCL ARC is, therefore, particularly exciting, in that we're both a research lab investigating - through the service provider's and tinkerer's epistemologies - how
best to use data and computers and software as research instruments, and as a reliable professional service with real market data. I think there's more we can learn about services close to a university's
academic mission in other areas besides IT from the success of UCL ARC.

:::

## 2.24 My appointment and the validation of these epistemologies
::: notes

It's been a challenging journey to establish the research-IT-as-academic-and-professional identity in the institutions I've worked for. 

It's pushed against the grain of separation of the academic and professional cultures.

It's also pushed against the trends of academia itself - epistemic diversity requires recognition of new forms of research output - the tinkerer's github pull request, the practicing engineers' architectural standards
document, a management policy document on professional models for staff scientists - as valid research outputs alongside traditional research papers. Colleagues, such as Simon Hettrick's "Hidden REF" work
have been critical.

One of the things I'm proud of about working for University College London is that it's been challenging the rules of academia since it's foundation - admitting women and religious nonconformists for example - and
I'm pleased that my appointment as professor recognises that the approaches to scholarship that I've championed are fully valued at the third best university in Europe. (According to one fairly spurious benchmark.)

:::
